name: monitoring
namespace: monitoring
namespaceLabels:
  space: service
space: service
description: All the monitoring apps, including but not limited to prometheus, grafana, thanos, loki.

apps:
  - name: cortex
    source:
      repoURL: 'https://distributed-technologies.github.io/helm-charts/'
      targetRevision: 0.1.3
      chart: cortex
      valuesFile: "cortex.yaml"
  - name: grafana
    source:
      repoURL: 'https://distributed-technologies.github.io/helm-charts/'
      targetRevision: 0.1.13
      chart: grafana
      valuesFile: "grafana.yaml"
  - name: prometheus
    source:
      repoURL: 'https://distributed-technologies.github.io/helm-charts/'
      targetRevision: 0.1.6
      chart: prometheus
      valuesFile: "prometheus.yaml"
  - name: promtail
    source:
      repoURL: 'https://distributed-technologies.github.io/helm-charts/'
      targetRevision: 0.1.0
      chart: promtail
      valuesFile: "promtail.yaml"
  - name: loki
    source:
      repoURL: 'https://distributed-technologies.github.io/helm-charts/'
      targetRevision: 1.0.1
      chart: loki
      valuesFile: "loki.yaml"
  - name: tempo
    source:
      repoURL: 'https://distributed-technologies.github.io/helm-charts/'
      targetRevision: 0.1.1
      chart: tempo-distributed
      valuesFile: "tempo.yaml"
  - name: monitoring-stack
    source:
      repoURL: 'https://github.com/distributed-technologies/helm-charts'
      targetRevision: feature/monitoring-stack
      path: charts/monitoring-stack/chart
      valuesFile: "monitoring-stack.yaml"
