name: monitoring
namespace: monitoring
namespaceLabels:
  space: service
space: service
description: All the monitoring apps, including but not limited to prometheus, grafana, thanos, loki.

apps:
  - name: cortex
    source:
      repoURL: 'https://distributed-technologies.github.io/helm-charts/'
      targetRevision: 0.1.2
      chart: cortex
      valuesFile: "cortex.yaml"
  - name: grafana
    source:
      repoURL: 'https://distributed-technologies.github.io/helm-charts/'
      targetRevision: 0.1.10
      chart: grafana
      valuesFile: "grafana.yaml"
    ingress:
      - subDomain: grafana
        path: /
        servicePort: 80
        serviceName: grafana
        annotation:
          traefik.ingress.kubernetes.io/router.entrypoints: web
  - name: prometheus
    source:
      repoURL: 'https://github.com/distributed-technologies/helm-charts'
      targetRevision: feature/grafana-agent-replacement
      path: charts/prometheus/chart
      # repoURL: 'https://distributed-technologies.github.io/helm-charts/'
      # targetRevision: 0.1.4
      # chart: prometheus
      valuesFile: "prometheus.yaml"
  - name: promtail
    source:
      repoURL: 'https://github.com/distributed-technologies/helm-charts'
      targetRevision: feature/grafana-agent-replacement
      path: charts/promtail/chart
      # repoURL: 'https://distributed-technologies.github.io/helm-charts/'
      # targetRevision: 0.1.4
      # chart: prometheus
      valuesFile: "promtail.yaml"
  - name: exporters
    source:
      repoURL: 'https://github.com/distributed-technologies/helm-charts'
      targetRevision: feature/add-service-monitors
      path: charts/exporters/chart
      # repoURL: 'https://distributed-technologies.github.io/helm-charts/'
      # targetRevision: 0.1.4
      # chart: prometheus
      valuesFile: "exporters.yaml"
  - name: loki
    source:
      repoURL: 'https://distributed-technologies.github.io/helm-charts/'
      targetRevision: 1.0.0
      chart: loki
      valuesFile: "loki.yaml"
  - name: tempo
    source:
      repoURL: 'https://distributed-technologies.github.io/helm-charts/'
      targetRevision: 0.1.1
      chart: tempo-distributed
      valuesFile: "tempo.yaml"
