name: monitoring
namespace: monitoring
namespaceLabels:
  space: service
space: service
description: All the monitoring apps, including but not limited to prometheus, grafana, thanos, loki.

apps:
  - name: grafana-agent
    source:
      repoURL: 'https://distributed-technologies.github.io/helm-charts/'
      targetRevision: 0.1.1
      chart: grafana-agent
      valuesFile: "grafana-agent.yaml"
  - name: grafana
    source:
      repoURL: 'https://distributed-technologies.github.io/helm-charts/'
      targetRevision: 0.1.10
      chart: grafana
      valuesFile: "grafana.yaml"
    ingress:
      - subDomain: grafana
        path: /
        servicePort: 80
        serviceName: grafana
        annotation:
          traefik.ingress.kubernetes.io/router.entrypoints: web
  - name: loki
    source:
      repoURL: 'https://distributed-technologies.github.io/helm-charts/'
      targetRevision: 1.0.0
      chart: loki
      valuesFile: "loki.yaml"
  - name: tempo
    source:
      repoURL: 'https://distributed-technologies.github.io/helm-charts/'
      targetRevision: 0.1.1
      chart: tempo-distributed
      valuesFile: "tempo.yaml"
  - name: cortex
    source:
      repoURL: 'https://distributed-technologies.github.io/helm-charts/'
      targetRevision: 0.1.2
      chart: cortex
      valuesFile: "cortex.yaml"
