name: monitoring
namespace: monitoring
namespaceLabels:
  space: service
space: service
description: All the monitoring apps, including but not limited to prometheus, grafana, thanos, loki.

apps:
  - name: cortex
    source:
      repoURL: 'https://github.com/distributed-technologies/helm-charts' # TODO Change this
      targetRevision: bug/ceph-bucket-claim # TODO Changes this
      # chart: tempo-distributed # TODO Comment back in
      path: charts/cortex/chart
      valuesFile: "cortex.yaml"
  - name: grafana
    source:
      repoURL: 'https://distributed-technologies.github.io/helm-charts/'
      targetRevision: 0.1.10
      chart: grafana
      valuesFile: "grafana.yaml"
    ingress:
      - subDomain: grafana
        path: /
        servicePort: 80
        serviceName: grafana
        annotation:
          traefik.ingress.kubernetes.io/router.entrypoints: web
  - name: grafana-agent
    source:
      repoURL: 'https://distributed-technologies.github.io/helm-charts/'
      targetRevision: 0.1.1
      chart: grafana-agent
      valuesFile: "grafana-agent.yaml"
  - name: loki
    source:
      repoURL: 'https://distributed-technologies.github.io/helm-charts/'
      targetRevision: 0.1.2
      chart: loki
      valuesFile: "loki.yaml"
  - name: tns
    source:
      repoURL: 'https://github.com/distributed-technologies/helm-charts' # TODO Change this
      targetRevision: feature/tns # TODO Changes this
      # chart: tempo-distributed # TODO Comment back in
      path: charts/tns/chart
      valuesFile: "tns.yaml"
