kube-prometheus-stack:
  grafana:
    enabled: false
  {{- if .Values.registry }}
  alertmanager: 
    alertmanagerSpec:
      image: 
        repository: {{ .Values.registry }}/prometheus/alertmanager
        tag: v0.22.0
  prometheusOperator:
    admissionWebhooks: 
      patch:
        image: 
          repository: {{ .Values.registry }}/jettech/kube-webhook-certgen
          tag: v1.5.2
    image: 
      repository: {{ .Values.registry }}/prometheus-operator/prometheus-operator 
    prometheusConfigReloaderImage: 
      repository: {{ .Values.registry }}/prometheus-operator/prometheus-config-reloader
  {{- end }}

  prometheus: 
    prometheusSpec: 
      replicas: 3
  {{- if .Values.registry }}
      image: 
        repository: {{ .Values.registry }}/prometheus/prometheus

  kube-state-metrics: 
    image:
      repository: {{ .Values.registry }}/kube-state-metrics/kube-state-metrics

  prometheus-node-exporter:
    image:
      repository: {{ .Values.registry }}/prometheus/node-exporter
  {{- end }}
