name: loadbalancer
namespace: loadbalancer
namespaceLabels:
  space: service
space: service
description: MetalLB loadbalancer.

apps:
  - name: loadbalancer
    source:
      repoURL: "https://github.com/distributed-technologies/services-loadbalancer.git"
      targetRevision: v0.1.5
      path: chart
      valuesFile: "loadbalancer.yaml"
