name: networking
namespace: networking
namespaceLabels:
  space: service
space: service
description: networking services like ingress, cert-manager.

apps:
  - name: ingress
    source:
      repoURL: "https://distributed-technologies.github.io/helm-charts/"
      targetRevision: 0.2.5
      chart: traefik
      valuesFile: "ingress.yaml"
  - name: external-dns
    source:
      repoURL: 'https://distributed-technologies.github.io/helm-charts/'
      targetRevision: 0.1.0
      chart: external-dns
      valuesFile: "external-dns.yaml"
