apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: eo-base
  namespace: default
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  # The project the application belongs to.
  project: default

  # Source of the application manifests
  source:
    repoURL: "{{ .Values.repoURL }}"
    targetRevision: {{ .Values.targetRevision }} 
    path: eo-base

    helm:
      version: v3
      values: |
        ingressDomain: {{ .Values.ingressDomain }}
        {{- if (.Values.ingress).cors }}
        ingress:
          cors: 
          {{- with .Values.ingress.cors }}
          {{- toYaml . | nindent 10 }}
          {{- end }}
        {{- end }}
        {{- with index .Values "eo-base" }}
        {{- toYaml . | nindent 8 }}
        {{- end }}

  # Destination cluster and namespace to deploy the application
  destination:
    server: https://kubernetes.default.svc
    namespace: default

  # Sync policy
  syncPolicy:
    automated: # automated sync by default retries failed attempts 5 times with following delays between attempts ( 5s, 10s, 20s, 40s, 80s ); retry controlled using `retry` field.
      prune: true # Specifies if resources should be pruned during auto-syncing ( false by default ).
      selfHeal: true # Specifies if partial app sync should be executed when resources are changed only in target Kubernetes cluster and no git change detected ( false by default ).
