name: rook-ceph
namespace: rook-ceph
namespaceLabels:
  space: service
space: service
description: Rook.

apps:
  - name: rook
    source:
      repoURL: "https://distributed-technologies.github.io/helm-charts/"
      targetRevision: 0.1.3
      chart: rook
      valuesFile: "rook.yaml"
  - name: ceph
    source:
      repoURL: "https://distributed-technologies.github.io/helm-charts/"
      targetRevision: 0.1.6
      chart: rook-ceph-cluster
      valuesFile: "ceph.yaml"
  - name: ntp
    source:
      repoURL: "https://distributed-technologies.github.io/helm-charts/"
      targetRevision: 0.1.4
      chart: ntp
      valuesFile: "ntp.yaml"
