name: kafka
namespace: kafka
namespaceLabels:
  space: service
space: service
description: Kafka.

apps:
  - name: kafka
    replace: true
    source:
      repoURL: "https://github.com/distributed-technologies/confluent-kafka.git"
      targetRevision: main
      chart: kafka
      valuesFile: "kafka.yaml"
