name: kafka
namespace: kafka
namespaceLabels:
  space: service
space: service
description: Kafka.

apps:
  - name: kafka
    replace: true
    source:
      repoURL: "https://github.com/distributed-technologies/helm-charts.git"
      targetRevision: v0.3.3
      path: charts/kafka
      valuesFile: "kafka.yaml"
