name: kafka
namespace: kafka
namespaceLabels:
  space: service
space: service
description: Kafka.

apps:
  - name: kafka
    replace: true
    source:
      repoURL: "https://github.com/distributed-technologies/services-kafka.git"
      targetRevision: v0.3.1
      path: chart
      valuesFile: "kafka.yaml"
