name: kafka
clusterService: true
namespace: kafka
description: Kafka.

project:
  name: kafka
  server: https://kubernetes.default.svc
  sourceRepos:
    - '*'

apps:
  - name: kafka
    replace: true
    source:
      repoURL: "kahyt.azurecr.io/test-repo/test"
      targetRevision: v0.1.0
      path: chart
      enableOCI: true
