apiVersion: v2
name: nidhogg
description: A Helm chart for nidhogg values and dependencies
type: application
version: 2.0.24

dependencies:
  - name: nidhogg
    version: 1.0.18
    repository: "http://192.168.65.20:8080"
