name: Lint charts

"on": pull_request

jobs:
  lint-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Helm
        uses: azure/setup-helm@v1

      - name: Set up python
        uses: actions/setup-python@v2
        with:
          python-version: 3.7

      - name: Setup chart-testing
        uses: helm/chart-testing-action@v2.1.0

      - name: Run chart-testing (lint)
        run: ct lint --debug --config ./.github/configs/ct-lint.yaml --lint-conf ./.github/configs/lintconf.yaml

      - name: Check matching version
        run: "awk 'NR==FNR && /^version:/ { gsub(/\"/, \"\", $2); v=$2; print (\"Yggdrasil version: \" v); next } /^version:/ { gsub(/\"/, \"\", $2); print (\"Nidhogg version: \" $2); if (v!=$2) { print \"Error: versions do not match\"; exit 1 } }' ./yggdrasil/Chart.yaml ./nidhogg/Chart.yaml"
